
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout script
        run: ls -l
      - name: qemu 
        uses: docker/setup-qemu-action@v1
      - name: docker buildbox
        uses: docker/setup-buildx-action@1
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: $((secrets.DOCKER_PASSWORD}}
      - name: build push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maskmafia/pycicd:latest
