
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]
#  schedule:
#    - cron: '*/8 * * * *'

jobs:
  gate-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout script
        run: |
          ls -a
          ./bin/time_validation.sh
          echo ${{ job.status }} 
  build:
     needs: gate-check
     runs-on: ubuntu:latest
     steps:
       - name: Build & push Docker image
         uses: mr-smithers-excellent/docker-build-push@v5
         with:
           image: maskmafia/pycicd
           tags: v1, latest
           registry: docker.io
           dockerfile: Dockerfile
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
